import React, { useEffect, useState } from "react";
import { BadgeCheck, CheckCircle2, ChevronRight, CreditCard, KeyRound, Landmark, LockKeyhole, Mail, ShieldCheck, UserPlus, X } from "lucide-react";

const rights = [["Chuyên đề Cấu trúc dữ liệu", "Quyền học cá nhân", "Còn hiệu lực đến 30/06/2027", "emerald"], ["Tuyển tập đề HSG các tỉnh", "Quyền học cá nhân", "Sắp hết hạn sau 28 ngày", "amber"], ["Chuyên đề Đồ thị", "Chưa kích hoạt", "Chưa có quyền để đọc/làm bài", "slate"]];

export default function AccessCenterModal({ isOpen, mode = "auth", onClose, userRole }) {
  const [view, setView] = useState(mode);
  const [step, setStep] = useState("scope");
  const [scope, setScope] = useState(userRole === "teacher" ? "teacher" : "student");
  const [payment, setPayment] = useState("vnpay");
  useEffect(() => { if (isOpen) { setView(mode); setStep(mode === "checkout" ? "scope" : "start"); } }, [isOpen, mode]);
  if (!isOpen) return null;
  const close = () => { setView(mode); setStep("scope"); onClose(); };
  const teacher = scope === "teacher";
  const shell = (title, subtitle, body) => <div className="fixed inset-0 z-[75] flex items-center justify-center bg-slate-950/55 p-3 sm:p-6" role="dialog" aria-modal="true"><div className="max-h-[92vh] w-full max-w-xl overflow-y-auto rounded-3xl bg-white shadow-2xl"><header className="sticky top-0 z-10 flex items-start gap-3 border-b border-slate-100 bg-white/95 px-5 py-4 backdrop-blur"><span className="grid h-10 w-10 place-items-center rounded-xl bg-blue-50 text-blue-600"><ShieldCheck className="h-5 w-5"/></span><div className="min-w-0 flex-1"><h2 className="text-base font-black text-slate-800">{title}</h2><p className="mt-1 text-[11px] text-slate-500">{subtitle}</p></div><button onClick={close} className="rounded-xl p-2 text-slate-500 hover:bg-slate-100" aria-label="Đóng"><X className="h-5 w-5"/></button></header>{body}</div></div>;
  const auth = (signup = false) => shell(signup ? "Tạo tài khoản Ôn Thi 360" : "Đăng nhập để tiếp tục", signup ? "Tạo một hồ sơ để lưu tiến độ, quyền và kết quả học tập." : "Lưu kết quả, quản lý quyền học và theo dõi tiến độ của bạn.", <form className="space-y-3 p-5" onSubmit={e => { e.preventDefault(); close(); }}>{signup && <label className="block text-[11px] font-bold text-slate-700">Họ và tên<input required className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-3 text-sm outline-none focus:ring-2 focus:ring-blue-300" placeholder="Nguyễn Minh Anh"/></label>}<label className="block text-[11px] font-bold text-slate-700">Email hoặc số điện thoại<input required className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-3 text-sm outline-none focus:ring-2 focus:ring-blue-300" placeholder="minhanh@example.com"/></label><label className="block text-[11px] font-bold text-slate-700">Mật khẩu<input required type="password" minLength="6" className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-3 text-sm outline-none focus:ring-2 focus:ring-blue-300" placeholder="Tối thiểu 6 ký tự"/></label>{!signup && <button type="button" onClick={() => setView("forgot")} className="text-[11px] font-bold text-blue-600">Quên mật khẩu?</button>}{signup && <label className="flex gap-2 text-[11px] text-slate-600"><input required type="checkbox"/>Tôi đồng ý Điều khoản sử dụng và Chính sách bảo mật.</label>}<button className="w-full rounded-xl bg-blue-600 py-3 text-xs font-bold text-white">{signup ? "Tạo tài khoản" : "Đăng nhập"}</button><p className="text-center text-[11px] text-slate-500">{signup ? "Đã có tài khoản?" : "Chưa có tài khoản?"} <button type="button" onClick={() => setView(signup ? "auth" : "register")} className="font-bold text-blue-600">{signup ? "Đăng nhập" : "Đăng ký"}</button></p></form>);
  if (view === "auth") return auth();
  if (view === "register") return auth(true);
  if (view === "forgot") return shell("Khôi phục mật khẩu", "Chúng tôi sẽ gửi liên kết đặt lại mật khẩu nếu tài khoản tồn tại.", <form className="p-5" onSubmit={e => { e.preventDefault(); setView("resetSent"); }}><label className="block text-[11px] font-bold text-slate-700">Email hoặc số điện thoại<input required className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-3 text-sm outline-none focus:ring-2 focus:ring-blue-300" placeholder="minhanh@example.com"/></label><button className="mt-4 w-full rounded-xl bg-blue-600 py-3 text-xs font-bold text-white">Gửi liên kết khôi phục</button><button type="button" onClick={() => setView("auth")} className="mt-3 w-full text-xs font-bold text-blue-600">Quay lại đăng nhập</button></form>);
  if (view === "resetSent") return shell("Kiểm tra hộp thư", "Liên kết khôi phục có hiệu lực trong 15 phút.", <div className="p-6 text-center"><Mail className="mx-auto h-12 w-12 text-blue-500"/><p className="mt-3 text-xs text-slate-600">Nếu chưa thấy thư, hãy kiểm tra Spam hoặc thử lại sau 60 giây.</p><button onClick={close} className="mt-5 rounded-xl bg-blue-600 px-4 py-2.5 text-xs font-bold text-white">Đã hiểu</button></div>);
  if (view === "locked") return shell("Nội dung đang bị khóa", "Bài này cần đủ quyền học và tiến độ lớp để mở.", <div className="p-5"><div className="rounded-2xl border border-amber-100 bg-amber-50 p-4"><div className="flex gap-2"><LockKeyhole className="h-4 w-4 shrink-0 text-amber-600"/><div><p className="text-xs font-black text-amber-800">Bạn chưa kích hoạt “Chuyên đề Đồ thị”</p><p className="mt-1 text-[11px] text-slate-600">Sau khi có quyền học, giáo viên vẫn mở bài theo tiến độ lớp.</p></div></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><button onClick={() => setView("checkout")} className="rounded-xl bg-blue-600 py-3 text-xs font-bold text-white">Mua quyền học</button><button onClick={() => setView("activation")} className="rounded-xl border border-blue-200 py-3 text-xs font-bold text-blue-600">Nhập mã kích hoạt</button></div></div>);
  if (view === "activation") return shell("Kích hoạt quyền", "Mã chỉ được cấp sau khi đơn hợp lệ hoặc do đơn vị tổ chức lớp gửi.", <div className="p-5"><label className="block text-[11px] font-bold text-slate-700">Mã kích hoạt<input className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-3 font-mono text-sm uppercase tracking-wider outline-none focus:ring-2 focus:ring-blue-300" placeholder="OT360-XXXX-XXXX"/></label><div className="mt-3 rounded-xl bg-sky-50 p-3 text-[11px] text-slate-600">Mã quyền học cá nhân không thể chuyển thành quyền dạy và ngược lại.</div><button onClick={() => setView("rights")} className="mt-4 w-full rounded-xl bg-blue-600 py-3 text-xs font-bold text-white">Kiểm tra & kích hoạt</button></div>);
  if (view === "rights") return shell("Quyền của tôi", "Theo dõi phạm vi, thời hạn và lịch sử cấp quyền.", <div className="space-y-3 p-5">{rights.map(([name, type, note, tone]) => <button key={name} onClick={() => tone === "slate" && setView("locked")} className="flex w-full gap-3 rounded-2xl border border-slate-100 p-4 text-left hover:border-blue-200"><span className={`grid h-9 w-9 place-items-center rounded-xl ${tone === "emerald" ? "bg-emerald-50 text-emerald-600" : tone === "amber" ? "bg-amber-50 text-amber-600" : "bg-slate-100 text-slate-500"}`}><KeyRound className="h-4 w-4"/></span><span className="min-w-0 flex-1"><span className="block text-xs font-black text-slate-800">{name}</span><span className="mt-1 block text-[10px] text-slate-500">{type} · {note}</span></span><ChevronRight className="mt-2 h-4 w-4 text-slate-300"/></button>)}<button onClick={() => setView("checkout")} className="w-full rounded-xl border border-blue-200 bg-blue-50 py-3 text-xs font-bold text-blue-700">Mua thêm quyền truy cập</button></div>);
  if (view === "checkout") {
    if (step === "success") return shell("Đơn đã được tạo", "Trạng thái đơn và mã sẽ xuất hiện trong Quyền của tôi.", <div className="p-6 text-center"><CheckCircle2 className="mx-auto h-12 w-12 text-emerald-500"/><h3 className="mt-3 text-lg font-black text-slate-800">Đang chờ xác nhận thanh toán</h3><p className="mt-2 text-xs text-slate-500">Sau khi thanh toán hợp lệ, hệ thống tạo mã kích hoạt đúng scope đã chọn.</p><button onClick={() => setView("rights")} className="mt-5 rounded-xl bg-blue-600 px-4 py-2.5 text-xs font-bold text-white">Xem quyền của tôi</button></div>);
    if (step === "payment") return shell("Thanh toán đơn hàng", "Đơn #OT360-2026-0910 · Thao tác thanh toán là mô phỏng UI.", <div className="p-5"><div className="space-y-2">{[["vnpay", "VNPAY", CreditCard, "Chuyển tới cổng VNPAY"], ["bank", "Chuyển khoản ngân hàng", Landmark, "Xác nhận thủ công theo nội dung chuyển khoản"]].map(([id,label,Icon,note]) => <button key={id} onClick={() => setPayment(id)} className={`flex w-full items-center gap-3 rounded-2xl border p-3 text-left ${payment === id ? "border-blue-500 bg-blue-50" : "border-slate-200"}`}><Icon className="h-5 w-5 text-blue-600"/><span><span className="block text-xs font-bold text-slate-800">{label}</span><span className="text-[10px] text-slate-500">{note}</span></span><span className={`ml-auto h-4 w-4 rounded-full border-4 ${payment === id ? "border-blue-600" : "border-slate-200"}`}/></button>)}</div><div className="mt-4 rounded-xl bg-slate-50 p-3 text-[11px] text-slate-600"><b>Tổng thanh toán: 1.200.000đ</b><br/>Scope: {teacher ? "Quyền dạy mọi lớp phụ trách" : "Quyền học cá nhân"} · 365 ngày</div><button onClick={() => setStep("success")} className="mt-4 w-full rounded-xl bg-blue-600 py-3 text-xs font-bold text-white">{payment === "vnpay" ? "Mở VNPAY (mô phỏng)" : "Tôi đã chuyển khoản"}</button><button onClick={() => setStep("scope")} className="mt-3 w-full text-xs font-bold text-slate-500">Quay lại</button></div>);
    return shell("Mua quyền truy cập", "Chọn đúng phạm vi quyền trước khi tạo đơn.", <div className="p-5"><div className="grid gap-3 sm:grid-cols-2"><button onClick={() => setScope("student")} className={`rounded-2xl border p-4 text-left ${scope === "student" ? "border-blue-500 bg-blue-50" : "border-slate-200"}`}><UserPlus className="h-5 w-5 text-blue-600"/><p className="mt-2 text-xs font-black text-slate-800">Học cá nhân</p><p className="mt-1 text-[10px] text-slate-500">Đọc, làm và tự luyện nội dung trong thời hạn.</p></button><button onClick={() => setScope("teacher")} className={`rounded-2xl border p-4 text-left ${teacher ? "border-blue-500 bg-blue-50" : "border-slate-200"}`}><BadgeCheck className="h-5 w-5 text-blue-600"/><p className="mt-2 text-xs font-black text-slate-800">Dùng để dạy</p><p className="mt-1 text-[10px] text-slate-500">Gắn học liệu vào mọi lớp phụ trách.</p></button></div><div className="mt-4 rounded-xl border border-sky-100 bg-sky-50 p-3 text-[11px] text-slate-600"><b>{teacher ? "Quyền dạy mọi lớp phụ trách · 365 ngày" : "Quyền học cá nhân · 365 ngày"}</b><br/>{teacher ? "Không cấp quyền học cho học sinh." : "Không có quyền gắn học liệu vào lớp."}</div><label className="mt-3 flex gap-2 text-[11px] text-slate-600"><input type="checkbox"/>Mua kèm bản in (tùy chọn)</label><button onClick={() => setStep("payment")} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-blue-600 py-3 text-xs font-bold text-white"><CreditCard className="h-4 w-4"/>Tiếp tục thanh toán</button></div>);
  }
  return shell("Cửa truy cập", "Trang này chưa được cấu hình.", <div className="p-5 text-center"><button onClick={close} className="rounded-xl bg-blue-600 px-4 py-2 text-xs font-bold text-white">Đóng</button></div>);
}
