import React, { useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, BadgeCheck, BookOpen, CheckCircle2, ChevronRight, CreditCard, Eye, EyeOff, KeyRound, Landmark, LockKeyhole, Mail, Phone, ShieldCheck, Sparkles, UserPlus, Users, X } from "lucide-react";

const field = "mt-1.5 w-full min-h-12 rounded-2xl border border-[#D5E3E9] bg-white px-4 py-3 text-[13px] font-medium text-[#183D5E] outline-none transition placeholder:text-[#8193A3] hover:border-[#B8D0DB] focus:border-[#2D7FA3] focus:ring-4 focus:ring-[#DDF1F6]";
const primary = "flex min-h-12 w-full items-center justify-center gap-2 rounded-2xl bg-gradient-to-r from-[#126F91] to-[#188DB0] px-4 py-3 text-[12px] font-extrabold text-white shadow-[0_8px_18px_rgba(18,111,145,0.2)] transition hover:from-[#0F607E] hover:to-[#147D9B] focus:outline-none focus-visible:ring-4 focus-visible:ring-[#CBEAF1] active:scale-[.98]";
const rights = [["Chuyên đề Cấu trúc dữ liệu", "Quyền học cá nhân", "Còn hiệu lực đến 30/06/2027", "emerald"], ["Tuyển tập đề HSG các tỉnh", "Quyền học cá nhân", "Sắp hết hạn sau 28 ngày", "amber"], ["Chuyên đề Đồ thị", "Chưa kích hoạt", "Chưa có quyền để đọc/làm bài", "slate"]];
const registerRoles = [
  ["student", "Học sinh", "Theo lộ trình, luyện tập và lưu kết quả", BookOpen],
  ["parent", "Phụ huynh", "Theo dõi con sau khi xác minh liên kết", Users],
  ["teacher", "Giáo viên", "Tạo hồ sơ giảng dạy và gửi yêu cầu phê duyệt", BadgeCheck],
];

function ArtPanel() {
  return <aside className="relative hidden min-h-[620px] overflow-hidden bg-[#0574ca] lg:flex lg:flex-col lg:justify-between">
    <img src="/assets/auth-learning-welcome-v1.png" alt="Học sinh học lập trình cùng Ôn Thi 360" className="absolute inset-0 h-full w-full object-cover object-right" />
    <div className="absolute inset-0 bg-gradient-to-br from-[#0056a8]/95 via-[#006fc8]/75 to-[#15b8df]/20" />
    <div className="relative p-8 xl:p-10 text-white"><div className="inline-flex items-center gap-2 rounded-full border border-white/25 bg-white/15 px-3 py-1.5 text-[11px] font-bold backdrop-blur"><Sparkles className="h-3.5 w-3.5 text-amber-300" />Học cùng mục tiêu, vươn xa ước mơ</div><h2 className="mt-6 max-w-sm text-2xl font-black leading-tight tracking-tight text-white xl:text-3xl">Mỗi bước học tập đều được lưu lại.</h2><p className="mt-3 max-w-sm text-xs leading-5 text-sky-50">Từ bài luyện đầu tiên đến hành trình chinh phục mục tiêu — Ôn Thi 360 đồng hành cùng bạn.</p></div>
    <div className="relative m-6 mt-0 grid grid-cols-3 gap-2 rounded-2xl border border-white/25 bg-slate-950/10 p-3 backdrop-blur-md xl:m-8">{[["12+", "Môn học"], ["2.4k", "Bài luyện"], ["98%", "Hài lòng"]].map(([n, l]) => <div key={l} className="text-center"><p className="text-lg font-black text-white">{n}</p><p className="text-[11px] font-medium text-sky-100">{l}</p></div>)}</div>
  </aside>;
}

function AuthShell({ title, eyebrow, children, onClose, compact = false }) {
  return <div className="auth-shell fixed inset-0 z-[75] flex items-center justify-center overflow-y-auto bg-slate-950/60 p-2 backdrop-blur-[3px] sm:p-5" role="dialog" aria-modal="true"><div className={`relative my-auto grid max-h-[min(96dvh,740px)] w-full overflow-hidden rounded-3xl border border-white/60 bg-white shadow-[0_24px_70px_rgba(7,44,72,0.28)] ${compact ? "max-w-xl" : "max-w-5xl lg:grid-cols-[1.05fr_.95fr]"}`}>
    {!compact && <ArtPanel />}<section className={`relative min-w-0 overflow-y-auto bg-gradient-to-b from-white via-white to-[#F8FCFD] ${compact ? "" : "border-t-4 border-[#126F91] lg:max-h-[min(96dvh,740px)] lg:border-l lg:border-t-0 lg:border-[#E5F0F4]"}`}><button type="button" onClick={onClose} className="absolute right-3 top-3 z-10 grid h-10 w-10 place-items-center rounded-xl text-slate-400 transition hover:bg-slate-100 hover:text-slate-700 focus:outline-none focus-visible:ring-4 focus-visible:ring-sky-100" aria-label="Đóng"><X className="h-5 w-5" /></button><div className={`mx-auto w-full ${compact ? "p-5 sm:p-7" : "max-w-md p-4 sm:p-8 lg:px-9 lg:py-9"}`}>{!compact && <div className="flex items-center gap-2 text-[#126F91]"><span className="grid h-8 w-8 place-items-center rounded-xl border border-[#C9DFE8] bg-[#EAF5F8]"><ShieldCheck className="h-4 w-4" /></span><span className="text-[11px] font-black tracking-wide">ÔN THI 360</span></div>}<p className={`auth-eyebrow ${compact ? "" : "mt-3"} text-[10px] font-black uppercase tracking-[.16em] text-[#2D7FA3]`}>{eyebrow}</p><h2 className={`mt-1 pr-9 font-black leading-tight tracking-tight text-[#123B68] ${compact ? "text-base" : "text-xl sm:text-2xl"}`}>{title}</h2>{children}</div></section>
  </div></div>;
}

export default function AccessCenterModal({ isOpen, mode = "auth", onClose, userRole }) {
  const [view, setView] = useState(mode), [authMethod, setAuthMethod] = useState("email"), [showPassword, setShowPassword] = useState(false), [registerStep, setRegisterStep] = useState(1), [accountRole, setAccountRole] = useState("student"), [scope, setScope] = useState(userRole === "teacher" ? "teacher" : "student"), [payment, setPayment] = useState("vnpay"), [checkoutStep, setCheckoutStep] = useState("scope");
  useEffect(() => { if (isOpen) { setView(mode); setRegisterStep(1); setAccountRole("student"); setShowPassword(false); setCheckoutStep("scope"); } }, [isOpen, mode]);
  if (!isOpen) return null;
  const close = () => { setView(mode); onClose(); };
  const selector = <div role="tablist" aria-label="Phương thức đăng nhập" className="mt-4 grid grid-cols-2 gap-1 rounded-2xl border border-[#E4EFF3] bg-[#F3F7F9] p-1"><button type="button" role="tab" aria-selected={authMethod === "email"} onClick={() => setAuthMethod("email")} className={`flex min-h-10 items-center justify-center gap-1.5 rounded-xl text-xs font-bold transition-all focus:outline-none focus-visible:ring-2 focus-visible:ring-sky-200 ${authMethod === "email" ? "bg-white text-[#216F8E] shadow-[0_2px_7px_rgba(64,105,125,0.1)]" : "text-slate-500 hover:text-slate-700"}`}><Mail className="h-3.5 w-3.5" />Email</button><button type="button" role="tab" aria-selected={authMethod === "phone"} onClick={() => setAuthMethod("phone")} className={`flex min-h-10 items-center justify-center gap-1.5 rounded-xl text-xs font-bold transition-all focus:outline-none focus-visible:ring-2 focus-visible:ring-sky-200 ${authMethod === "phone" ? "bg-white text-[#216F8E] shadow-[0_2px_7px_rgba(64,105,125,0.1)]" : "text-slate-500 hover:text-slate-700"}`}><Phone className="h-3.5 w-3.5" />Số điện thoại</button></div>;
  const password = <label htmlFor="auth-password" className="auth-form-label mt-3 block text-[11px] font-bold text-slate-700">Mật khẩu<div className="relative"><input id="auth-password" required autoComplete="current-password" type={showPassword ? "text" : "password"} minLength="6" className={`${field} pr-12`} placeholder="Tối thiểu 6 ký tự"/><button type="button" onClick={() => setShowPassword(!showPassword)} aria-label={showPassword ? "Ẩn mật khẩu" : "Hiện mật khẩu"} className="absolute right-2 top-1/2 grid h-10 w-10 -translate-y-1/2 place-items-center rounded-xl text-slate-400 transition hover:bg-slate-50 hover:text-slate-700 focus:outline-none focus-visible:ring-2 focus-visible:ring-sky-200">{showPassword ? <EyeOff className="h-4 w-4"/> : <Eye className="h-4 w-4"/>}</button></div></label>;
  const contact = <label htmlFor="auth-contact" className="auth-form-label block text-[11px] font-bold text-slate-700">{authMethod === "email" ? "Email" : "Số điện thoại"}<input id="auth-contact" required autoComplete={authMethod === "email" ? "email" : "tel"} inputMode={authMethod === "email" ? "email" : "tel"} className={field} placeholder={authMethod === "email" ? "minhanh@example.com" : "098 123 4567"}/></label>;

  if (view === "auth") return (
    <AuthShell title="Đăng nhập" eyebrow="Tài khoản Ôn Thi 360" onClose={close}>
      {/* [AUTH-01] FORM ĐĂNG NHẬP — thứ tự đọc và thứ bậc CTA theo spec trang chủ */}
      <p className="mt-1.5 type-body leading-5 text-[#536D86]">Lưu tiến độ và tiếp tục học tập trên mọi thiết bị.</p>
      <div className="mt-1.5 flex items-center gap-1.5 text-[11px] leading-4 text-[#71869A]">
        <ShieldCheck className="h-3.5 w-3.5 shrink-0 text-[#2D7FA3]" />
        <span>Dữ liệu được lưu an toàn theo vai trò của bạn.</span>
      </div>
      {selector}
      <form className="mt-3" onSubmit={e => { e.preventDefault(); setView("loginSuccess"); }}>
        {contact}
        {password}
        <div className="mt-2.5 flex items-center justify-between gap-3">
          <label className="auth-form-helper flex items-center gap-2 text-[11px] text-slate-500"><input type="checkbox" className="h-4 w-4 rounded accent-[#126F91]"/>Ghi nhớ đăng nhập</label>
          <button type="button" onClick={() => setView("forgot")} className="auth-form-action text-[11px] font-bold text-[#126F91] hover:text-[#0F607E] hover:underline focus:outline-none focus-visible:ring-2 focus-visible:ring-sky-200">Quên mật khẩu?</button>
        </div>
        <button type="submit" className={`${primary} mt-4`}>Đăng nhập <ArrowRight className="h-4 w-4"/></button>
      </form>
      <div className="my-3 flex items-center gap-3 text-[10px] font-semibold text-slate-400 before:h-px before:flex-1 before:bg-slate-100 after:h-px after:flex-1 after:bg-slate-100">hoặc</div>
      <button type="button" className="flex min-h-12 w-full items-center justify-center gap-2 rounded-2xl border border-[#D5E3E9] bg-white px-4 py-3 text-xs font-bold text-[#183D5E] transition hover:border-[#B8D0DB] hover:bg-[#F8FCFD] focus:outline-none focus-visible:ring-4 focus-visible:ring-sky-100"><span className="grid h-6 w-6 place-items-center rounded-full bg-gradient-to-br from-red-500 via-amber-400 to-blue-500 text-[10px] font-black text-white">G</span>Tiếp tục với Google</button>
      <p className="auth-form-helper mt-3 text-center text-[11px] text-slate-500">Chưa có tài khoản? <button type="button" onClick={() => { setView("register"); setRegisterStep(1); }} className="auth-form-action font-black text-[#126F91] hover:text-[#0F607E] hover:underline focus:outline-none focus-visible:ring-2 focus-visible:ring-sky-200">Tạo tài khoản miễn phí</button></p>
    </AuthShell>
  );
  if (view === "loginSuccess") return <AuthShell compact title="Đăng nhập thành công" eyebrow="Sẵn sàng học tập" onClose={close}><div className="py-7 text-center"><span className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-emerald-50 text-emerald-500"><CheckCircle2 className="h-9 w-9"/></span><p className="type-body mx-auto mt-3 max-w-sm">Chào Minh Anh! Tiến độ học, bài đã lưu và quyền truy cập của bạn đã sẵn sàng.</p><button onClick={close} className={`${primary} mx-auto mt-5 max-w-xs`}>Vào trang học tập <ArrowRight className="h-4 w-4"/></button></div></AuthShell>;
  if (view === "register") return <AuthShell title={registerStep === 1 ? "Tạo tài khoản mới" : registerStep === 2 ? "Xác minh tài khoản" : "Bạn tham gia với vai trò nào?"} eyebrow={`Đăng ký · Bước ${registerStep}/3`} onClose={close}><div className="mt-4 flex items-center gap-2">{[1,2,3].map(n => <React.Fragment key={n}><span className={`grid h-6 w-6 place-items-center rounded-full text-[10px] font-black ${n <= registerStep ? "bg-blue-600 text-white" : "bg-slate-100 text-slate-400"}`}>{n < registerStep ? "✓" : n}</span>{n < 3 && <span className={`h-1 flex-1 rounded-full ${n < registerStep ? "bg-blue-500" : "bg-slate-100"}`}/>}</React.Fragment>)}</div>
    {registerStep === 1 && <form className="mt-3" onSubmit={e => { e.preventDefault(); setRegisterStep(2); }}><label className="auth-form-label block text-[11px] font-bold text-slate-700">Họ và tên<input required autoComplete="name" className={field} placeholder="Nguyễn Minh Anh"/></label>{selector}<div className="mt-2.5">{contact}</div>{password}<label className="auth-form-helper mt-2.5 flex items-start gap-2 text-[11px] leading-4 text-slate-600"><input required type="checkbox" className="mt-0.5 h-4 w-4 shrink-0 rounded accent-[#126F91]"/><span>Tôi đồng ý với <button type="button" className="font-bold text-blue-600 hover:underline">Điều khoản sử dụng</button> và <button type="button" className="font-bold text-blue-600 hover:underline">Chính sách bảo mật</button>.</span></label><button type="submit" className={`${primary} mt-3`}>Tiếp tục xác minh <ArrowRight className="h-4 w-4"/></button></form>}
    {registerStep === 2 && <div className="mt-5"><div className="rounded-2xl border border-sky-100 bg-sky-50 p-4"><Mail className="h-5 w-5 text-blue-600"/><p className="auth-form-label mt-1.5 text-[11px] font-bold text-slate-800">Mã xác minh đã được gửi</p><p className="auth-form-helper mt-1 text-[11px] leading-4 text-slate-500">Nhập 6 chữ số chúng tôi vừa gửi đến minhanh@example.com.</p></div><div className="mt-4 flex justify-between gap-2">{Array.from({ length: 6 }).map((_, i) => <input key={i} aria-label={`Chữ số ${i + 1}`} inputMode="numeric" maxLength="1" className="h-10 min-w-0 flex-1 rounded-xl border border-slate-200 text-center text-base font-black outline-none focus:border-blue-400 focus:ring-4 focus:ring-blue-100" placeholder="•"/>)}</div><button type="button" onClick={() => setRegisterStep(3)} className={`${primary} mt-4`}>Xác minh tài khoản <CheckCircle2 className="h-4 w-4"/></button><div className="auth-form-helper mt-2.5 flex justify-between text-[11px]"><button type="button" onClick={() => setRegisterStep(1)} className="font-bold text-slate-500">Quay lại</button><button type="button" className="auth-form-action font-bold text-blue-600">Gửi lại mã sau 00:58</button></div></div>}
    {registerStep === 3 && <div className="mt-4"><p className="type-body leading-5">Chọn một vai trò để cá nhân hoá lộ trình và quyền sử dụng. Bạn luôn có thể cập nhật trong hồ sơ.</p><div className="mt-3 space-y-2" role="radiogroup" aria-label="Vai trò đăng ký">{registerRoles.map(([id, label, note, Icon]) => <button type="button" role="radio" aria-checked={accountRole === id} key={id} onClick={() => setAccountRole(id)} className={`flex w-full items-center gap-3 rounded-2xl border p-3 text-left transition focus:outline-none focus-visible:ring-4 focus-visible:ring-sky-100 ${accountRole === id ? "border-[#2D7FA3] bg-[#EAF5F8]" : "border-slate-200 bg-white hover:border-[#C9DFE8] hover:bg-[#F8FAFB]"}`}><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl ${accountRole === id ? "bg-[#2D7FA3] text-white" : "bg-slate-100 text-slate-500"}`}><Icon className="h-5 w-5"/></span><span className="min-w-0"><span className="block text-xs font-black text-slate-800">{label}</span><span className="auth-form-helper mt-0.5 block text-[11px] leading-4 text-slate-500">{note}</span></span><span aria-hidden="true" className={`ml-auto grid h-5 w-5 shrink-0 place-items-center rounded-full border ${accountRole === id ? "border-[#2D7FA3] bg-[#2D7FA3] text-white" : "border-slate-300 bg-white"}`}>{accountRole === id && <CheckCircle2 className="h-3.5 w-3.5"/>}</span></button>)}</div><button type="button" onClick={() => setView("registerSuccess")} className={`${primary} mt-4`}>Hoàn tất tạo tài khoản <ArrowRight className="h-4 w-4"/></button></div>}<p className="auth-form-helper mt-3 text-center text-[11px] text-slate-500">Đã có tài khoản? <button type="button" onClick={() => setView("auth")} className="auth-form-action font-black text-blue-600 hover:underline">Đăng nhập</button></p></AuthShell>;
  if (view === "registerSuccess") { const selectedRoleLabel = registerRoles.find(([id]) => id === accountRole)?.[1] || "Học sinh"; return <AuthShell compact title="Chào mừng bạn đến với Ôn Thi 360" eyebrow="Tài khoản đã sẵn sàng" onClose={close}><div className="py-7 text-center"><CheckCircle2 className="mx-auto h-14 w-14 text-emerald-500"/><p className="type-body mt-3">Tài khoản <b className="text-slate-700">{selectedRoleLabel}</b> của bạn đã được xác minh. Hãy bắt đầu thiết lập mục tiêu học tập đầu tiên.</p><button onClick={close} className={`${primary} mx-auto mt-5 max-w-xs`}>Khám phá lộ trình <Sparkles className="h-4 w-4"/></button></div></AuthShell>; }
  if (view === "forgot") return <AuthShell compact title="Khôi phục mật khẩu" eyebrow="Quên mật khẩu" onClose={close}><p className="type-body mt-1.5">Nhập email hoặc số điện thoại. Chúng tôi sẽ gửi hướng dẫn đặt lại mật khẩu nếu tài khoản tồn tại.</p><form className="mt-4" onSubmit={e => { e.preventDefault(); setView("resetSent"); }}><label className="auth-form-label block text-[11px] font-bold text-slate-700">Email hoặc số điện thoại<input required className={field} placeholder="minhanh@example.com"/></label><button className={`${primary} mt-4`}>Gửi hướng dẫn khôi phục <Mail className="h-4 w-4"/></button><button type="button" onClick={() => setView("auth")} className="auth-form-action mx-auto mt-3 flex items-center gap-1 text-[11px] font-bold text-blue-600"><ArrowLeft className="h-3.5 w-3.5"/>Quay lại đăng nhập</button></form></AuthShell>;
  if (view === "resetSent") return <AuthShell compact title="Kiểm tra hộp thư" eyebrow="Đã gửi hướng dẫn" onClose={close}><div className="py-7 text-center"><span className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-sky-50 text-blue-600"><Mail className="h-8 w-8"/></span><p className="mt-4 text-sm leading-6 text-slate-500">Liên kết khôi phục có hiệu lực trong 15 phút. Nếu chưa thấy thư, hãy kiểm tra mục Spam.</p><button onClick={() => setView("resetPassword")} className="mt-5 text-xs font-bold text-blue-600">Mô phỏng: tôi đã mở liên kết</button></div></AuthShell>;
  if (view === "resetPassword") return <AuthShell compact title="Đặt lại mật khẩu" eyebrow="Bảo mật tài khoản" onClose={close}><form className="mt-6" onSubmit={e => { e.preventDefault(); setView("resetSuccess"); }}>{password}<label className="auth-form-label mt-4 block text-xs font-bold text-slate-700">Nhập lại mật khẩu<input required type="password" minLength="6" className={field} placeholder="Nhập lại mật khẩu mới"/></label><button className={`${primary} mt-5`}>Lưu mật khẩu mới <CheckCircle2 className="h-4 w-4"/></button></form></AuthShell>;
  if (view === "resetSuccess") return <AuthShell compact title="Đã đặt lại mật khẩu" eyebrow="Thành công" onClose={close}><div className="py-8 text-center"><CheckCircle2 className="mx-auto h-14 w-14 text-emerald-500"/><p className="mt-4 text-sm text-slate-500">Mật khẩu mới đã được lưu an toàn. Bạn có thể đăng nhập ngay.</p><button onClick={() => setView("auth")} className={`${primary} mx-auto mt-6 max-w-xs`}>Đăng nhập ngay</button></div></AuthShell>;

  const miniShell = (title, subtitle, body) => <AuthShell compact title={title} eyebrow={subtitle} onClose={close}>{body}</AuthShell>;
  if (view === "locked") return miniShell("Nội dung đang bị khóa", "Quyền truy cập", <div className="mt-5"><div className="rounded-2xl border border-amber-100 bg-amber-50 p-4 text-sm text-amber-800"><LockKeyhole className="mb-2 h-5 w-5"/><b>Bạn chưa kích hoạt “Chuyên đề Đồ thị”</b><p className="mt-1 text-xs text-slate-600">Sau khi có quyền học, giáo viên vẫn mở bài theo tiến độ lớp.</p></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><button onClick={() => setView("checkout")} className="rounded-xl bg-blue-600 py-3 text-xs font-bold text-white">Mua quyền học</button><button onClick={() => setView("activation")} className="rounded-xl border border-blue-200 py-3 text-xs font-bold text-blue-600">Nhập mã kích hoạt</button></div></div>);
  if (view === "activation") return miniShell("Kích hoạt quyền", "Mã quyền", <div className="mt-5"><label className="auth-form-label block text-xs font-bold text-slate-700">Mã kích hoạt<input className={`${field} font-mono uppercase tracking-wider`} placeholder="OT360-XXXX-XXXX"/></label><div className="mt-3 rounded-xl bg-sky-50 p-3 text-[11px] text-slate-600">Mã quyền học cá nhân không thể chuyển thành quyền dạy và ngược lại.</div><button onClick={() => setView("rights")} className={`${primary} mt-4`}>Kiểm tra & kích hoạt</button></div>);
  if (view === "rights") return miniShell("Quyền của tôi", "Quản lý truy cập", <div className="mt-5 space-y-3">{rights.map(([name, type, note, tone]) => <button key={name} onClick={() => tone === "slate" && setView("locked")} className="flex w-full gap-3 rounded-2xl border border-slate-100 p-4 text-left hover:border-blue-200"><span className={`grid h-9 w-9 place-items-center rounded-xl ${tone === "emerald" ? "bg-emerald-50 text-emerald-600" : tone === "amber" ? "bg-amber-50 text-amber-600" : "bg-slate-100 text-slate-500"}`}><KeyRound className="h-4 w-4"/></span><span className="min-w-0 flex-1"><span className="block text-xs font-black text-slate-800">{name}</span><span className="mt-1 block text-[10px] text-slate-500">{type} · {note}</span></span><ChevronRight className="mt-2 h-4 w-4 text-slate-300"/></button>)}<button onClick={() => setView("checkout")} className="w-full rounded-xl border border-blue-200 bg-blue-50 py-3 text-xs font-bold text-blue-700">Mua thêm quyền truy cập</button></div>);
  if (view === "checkout") return miniShell(checkoutStep === "success" ? "Đơn đã được tạo" : checkoutStep === "payment" ? "Thanh toán đơn hàng" : "Mua quyền truy cập", "Quyền học & quyền dạy", checkoutStep === "success" ? <div className="py-8 text-center"><CheckCircle2 className="mx-auto h-12 w-12 text-emerald-500"/><p className="mt-3 text-sm text-slate-500">Đang chờ xác nhận thanh toán. Mã sẽ xuất hiện trong Quyền của tôi.</p><button onClick={() => setView("rights")} className={`${primary} mt-5`}>Xem quyền của tôi</button></div> : checkoutStep === "payment" ? <div className="mt-5"><div className="space-y-2">{[["vnpay", "VNPAY", CreditCard], ["bank", "Chuyển khoản ngân hàng", Landmark]].map(([id, label, Icon]) => <button key={id} onClick={() => setPayment(id)} className={`flex w-full items-center gap-3 rounded-2xl border p-3 text-left ${payment === id ? "border-blue-500 bg-blue-50" : "border-slate-200"}`}><Icon className="h-5 w-5 text-blue-600"/><span className="text-xs font-bold text-slate-800">{label}</span><span className={`ml-auto h-4 w-4 rounded-full border-4 ${payment === id ? "border-blue-600" : "border-slate-200"}`}/></button>)}</div><div className="mt-4 rounded-xl bg-slate-50 p-3 text-[11px] text-slate-600"><b>Tổng thanh toán: 1.200.000đ</b><br/>365 ngày · {scope === "teacher" ? "Quyền dạy mọi lớp phụ trách" : "Quyền học cá nhân"}</div><button onClick={() => setCheckoutStep("success")} className={`${primary} mt-4`}>{payment === "vnpay" ? "Mở VNPAY (mô phỏng)" : "Tôi đã chuyển khoản"}</button><button onClick={() => setCheckoutStep("scope")} className="mx-auto mt-4 flex text-xs font-bold text-slate-500"><ArrowLeft className="mr-1 h-3.5 w-3.5"/>Quay lại</button></div> : <div className="mt-5"><div className="grid gap-3 sm:grid-cols-2">{[["student", "Học cá nhân", "Đọc, làm và tự luyện", UserPlus], ["teacher", "Dùng để dạy", "Gắn vào mọi lớp phụ trách", BadgeCheck]].map(([id, title, note, Icon]) => <button key={id} onClick={() => setScope(id)} className={`rounded-2xl border p-4 text-left ${scope === id ? "border-blue-500 bg-blue-50" : "border-slate-200"}`}><Icon className="h-5 w-5 text-blue-600"/><p className="mt-2 text-xs font-black text-slate-800">{title}</p><p className="mt-1 text-[10px] text-slate-500">{note}</p></button>)}</div><button onClick={() => setCheckoutStep("payment")} className={`${primary} mt-5`}>Tiếp tục thanh toán <CreditCard className="h-4 w-4"/></button></div>);
  return null;
}
