import React, { useState } from "react";
import { CheckCircle2, ChevronLeft, ChevronRight, CircleHelp, Clock3, Code2, Flag, Save, Send, X } from "lucide-react";

const questions = [
  { id: 1, type: "Trắc nghiệm", title: "Thuật toán nào tìm đường đi ngắn nhất từ một đỉnh?", state: "done" },
  { id: 2, type: "Điền đáp án", title: "Độ phức tạp của binary search là bao nhiêu?", state: "current" },
  { id: 3, type: "Lập trình", title: "Tìm số phần tử khác nhau trong mảng", state: "review" }
];

export default function AssessmentModal({ isOpen, onClose }) {
  const [active, setActive] = useState(1);
  const [answer, setAnswer] = useState("");
  const [submitted, setSubmitted] = useState(false);
  const current = questions.find(q => q.id === active) || questions[0];
  if (!isOpen) return null;

  if (submitted) return <div className="fixed inset-0 z-[70] bg-slate-950/55 p-3 sm:p-6 flex items-center justify-center"><div className="w-full max-w-3xl rounded-3xl bg-white overflow-hidden shadow-2xl"><div className="bg-gradient-to-r from-blue-700 to-sky-500 p-6 text-white"><p className="text-xs font-bold uppercase tracking-wider text-sky-100">Đề đã nộp</p><h2 className="mt-1 text-2xl font-black">Kết quả tạm tính: 72 / 100</h2><p className="mt-2 text-xs text-sky-100">Câu lập trình đang chấm. Điểm cuối cùng sẽ được cập nhật sau khi có verdict.</p></div><div className="grid sm:grid-cols-3 divide-y sm:divide-y-0 sm:divide-x divide-slate-100 p-4"><div className="p-3"><p className="text-[10px] text-slate-400 uppercase font-bold">Đã trả lời</p><p className="mt-1 text-2xl font-black text-emerald-600">2 / 3</p></div><div className="p-3"><p className="text-[10px] text-slate-400 uppercase font-bold">Đang chấm</p><p className="mt-1 text-2xl font-black text-amber-500">1 câu</p></div><div className="p-3"><p className="text-[10px] text-slate-400 uppercase font-bold">Thời gian làm</p><p className="mt-1 text-2xl font-black text-blue-600">32 phút</p></div></div><div className="p-5 flex justify-end"><button onClick={onClose} className="rounded-xl bg-blue-600 px-4 py-2.5 text-xs font-bold text-white cursor-pointer">Xem lịch sử nộp</button></div></div></div>;

  return <div className="fixed inset-0 z-[70] bg-slate-950/55 p-0 sm:p-5 flex items-center justify-center"><div className="w-full max-w-6xl h-full sm:h-[min(760px,calc(100vh-40px))] bg-white sm:rounded-3xl overflow-hidden shadow-2xl flex flex-col"><header className="shrink-0 px-4 sm:px-6 py-3 border-b border-slate-100 flex items-center gap-3"><button onClick={onClose} className="p-2 rounded-xl hover:bg-slate-100 cursor-pointer"><X className="w-5 h-5 text-slate-500" /></button><div className="min-w-0 flex-1"><p className="text-[10px] font-bold uppercase tracking-wider text-blue-600">Đề luyện tuần 4 · đã lưu tự động</p><h2 className="text-sm sm:text-base font-black text-slate-800 truncate">Kiểm tra chuyên đề Cấu trúc dữ liệu</h2></div><div className="hidden sm:flex items-center gap-2 rounded-xl bg-amber-50 px-3 py-2 text-amber-700"><Clock3 className="w-4 h-4"/><span className="text-xs font-black">01:27:42</span></div><button className="hidden sm:flex items-center gap-1.5 px-3 py-2 text-xs font-bold text-slate-600 rounded-xl hover:bg-slate-50"><Save className="w-4 h-4"/>Đã lưu</button><button onClick={() => setSubmitted(true)} className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-blue-600 text-xs font-bold text-white cursor-pointer"><Send className="w-4 h-4"/>Nộp bài</button></header>
    <div className="flex-1 min-h-0 grid md:grid-cols-[220px_minmax(0,1fr)]"><aside className="border-r border-slate-100 bg-slate-50 p-3 overflow-y-auto"><p className="px-2 text-[10px] uppercase font-bold tracking-wider text-slate-400">Điều hướng câu hỏi</p><div className="mt-3 space-y-2">{questions.map(q => <button key={q.id} onClick={() => setActive(q.id)} className={`w-full flex items-center gap-2 p-2.5 rounded-xl text-left transition-colors cursor-pointer ${q.id === active ? "bg-blue-600 text-white shadow-md" : "bg-white border border-slate-100 text-slate-700 hover:border-blue-200"}`}><span className={`w-6 h-6 grid place-items-center rounded-lg text-[11px] font-black ${q.id === active ? "bg-white/20" : q.state === "done" ? "bg-emerald-100 text-emerald-700" : q.state === "review" ? "bg-amber-100 text-amber-700" : "bg-slate-100"}`}>{q.state === "done" ? "✓" : q.id}</span><span className="min-w-0"><span className="block text-[10px] font-bold opacity-75">{q.type}</span><span className="block text-[11px] font-bold truncate">Câu {q.id}</span></span>{q.state === "review" && <Flag className="ml-auto w-3.5 h-3.5"/>}</button>)}</div><div className="mt-4 rounded-xl border border-blue-100 bg-blue-50 p-3"><p className="text-[10px] font-bold text-blue-700">Trạng thái</p><p className="mt-1 text-[10px] text-slate-500">✓ Đã trả lời · ⚑ Đánh dấu xem lại</p></div></aside>
      <main className="min-w-0 overflow-y-auto p-5 sm:p-7"><div className="max-w-3xl mx-auto"><div className="flex items-center gap-2"><span className="rounded-full bg-blue-50 px-2.5 py-1 text-[10px] font-bold text-blue-600">Câu {current.id} · {current.type}</span><button className="ml-auto text-[10px] text-amber-600 font-bold flex items-center gap-1"><Flag className="w-3.5 h-3.5"/>Đánh dấu xem lại</button></div><h3 className="mt-4 text-base sm:text-lg font-black text-slate-800 leading-snug">{current.title}</h3>{active === 1 && <div className="mt-5 grid gap-2">{["Dijkstra", "Kruskal", "Quick sort", "DFS"].map((x,i)=><label key={x} className={`flex items-center gap-3 rounded-xl border p-3 text-xs font-semibold cursor-pointer ${i === 0 ? "border-blue-400 bg-blue-50 text-blue-700" : "border-slate-200 hover:border-blue-200"}`}><input type="radio" name="q1" defaultChecked={i===0}/>{x}</label>)}</div>}{active === 2 && <div className="mt-5"><label className="block text-xs font-bold text-slate-700">Đáp án của bạn <span className="text-rose-500">*</span></label><input value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Ví dụ: O(log n)" className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-3 text-sm outline-none focus:ring-2 focus:ring-blue-300"/><p className="mt-2 text-[10px] text-slate-500">Nhập theo đúng định dạng. Hệ thống không phân biệt khoảng trắng thừa.</p></div>}{active === 3 && <div className="mt-5 rounded-2xl overflow-hidden border border-slate-800 bg-[#0f172a]"><div className="px-4 py-2 flex justify-between bg-slate-800 text-[10px] text-slate-300"><span>C++17</span><span>Nháp được lưu tự động</span></div><textarea defaultValue={'#include <bits/stdc++.h>\nusing namespace std;\n\nint main() {\n  // Viết lời giải tại đây\n  return 0;\n}'} className="w-full h-56 bg-[#0f172a] p-4 font-mono text-xs leading-6 text-sky-100 outline-none resize-none"/></div>}<div className="mt-8 flex items-center justify-between"><button onClick={() => setActive(Math.max(1,active-1))} className="flex items-center gap-1 rounded-xl px-3 py-2 text-xs font-bold text-slate-600 hover:bg-slate-100 cursor-pointer"><ChevronLeft className="w-4 h-4"/>Câu trước</button><button onClick={() => setActive(Math.min(3,active+1))} className="flex items-center gap-1 rounded-xl bg-blue-600 px-3 py-2 text-xs font-bold text-white cursor-pointer">Câu tiếp<ChevronRight className="w-4 h-4"/></button></div></div></main></div></div></div>;
}
