import React, { useState } from "react";
import { AlertCircle, Archive, BookOpen, CheckCircle2, ChevronRight, ClipboardCheck, CloudOff, Download, FileCheck2, FileText, LockKeyhole, Plus, RefreshCw, Send, ShieldCheck, Star, Upload, UserCheck, Users } from "lucide-react";

const Card = ({ children, className = "" }) => <section className={`rounded-3xl border border-sky-100 bg-white p-5 ${className}`}>{children}</section>;
const Heading = ({ icon: Icon = FileText, title, hint, action }) => <div className="mb-4 flex items-start justify-between gap-3"><div className="flex gap-2"><span className="grid h-8 w-8 place-items-center rounded-xl bg-blue-50 text-blue-600"><Icon className="h-4 w-4"/></span><div><h2 className="text-sm font-black text-slate-800">{title}</h2>{hint && <p className="mt-0.5 text-[10px] text-slate-500">{hint}</p>}</div></div>{action}</div>;

export function ReviewCenterPanel() {
  const [tab, setTab] = useState("mine");
  const [editing, setEditing] = useState(false);
  const tabs = [["mine", "Đánh giá của tôi"], ["eligible", "Đủ điều kiện"], ["blocked", "Chưa đủ điều kiện"]];
  return <Card><Heading icon={Star} title="Đánh giá trải nghiệm" hint="Chỉ hiển thị sau khi tài khoản đạt điều kiện trải nghiệm thực."/>
    <div className="flex gap-1 overflow-x-auto border-b border-slate-100 pb-3">{tabs.map(([id,label]) => <button key={id} onClick={() => setTab(id)} className={`whitespace-nowrap rounded-xl px-3 py-2 text-xs font-bold ${tab === id ? "bg-blue-600 text-white" : "text-slate-600 hover:bg-sky-50"}`}>{label}</button>)}</div>
    {tab === "mine" && <div className="mt-4 space-y-3">{[["Chuyên đề Cấu trúc dữ liệu", "Đã công bố", "★ 5 · Có thể sửa đến 19/09"], ["Lớp HSG Tin 10A1", "Đang kiểm duyệt", "Đã gửi 12/09 · chờ phản hồi"]].map(([name,status,note]) => <div key={name} className="flex flex-wrap items-center gap-3 rounded-2xl bg-slate-50 p-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-amber-50 text-amber-500"><Star className="h-4 w-4 fill-current"/></span><div className="min-w-44 flex-1"><p className="text-xs font-black text-slate-800">{name}</p><p className="mt-1 text-[10px] text-slate-500">{note}</p></div><span className="text-[10px] font-bold text-blue-600">{status}</span><button onClick={() => setEditing(true)} className="rounded-xl border border-blue-200 px-3 py-2 text-[10px] font-bold text-blue-600">Xem / sửa</button></div>)}</div>}
    {tab === "eligible" && <div className="mt-4 rounded-2xl border border-emerald-100 bg-emerald-50 p-4"><p className="text-xs font-black text-emerald-800">Bạn đủ điều kiện đánh giá “Tuyển tập đề HSG các tỉnh”</p><p className="mt-1 text-[11px] text-slate-600">Điều kiện: có quyền học và đã hoàn thành 5 bài liên quan.</p><button onClick={() => setEditing(true)} className="mt-3 rounded-xl bg-emerald-600 px-3 py-2 text-xs font-bold text-white">Viết đánh giá</button></div>}
    {tab === "blocked" && <div className="mt-4 rounded-2xl border border-amber-100 bg-amber-50 p-4"><p className="text-xs font-black text-amber-800">Chưa đủ điều kiện đánh giá</p><p className="mt-1 text-[11px] text-slate-600">Hoàn thành thêm 2 bài trong “Chuyên đề Đồ thị” để chia sẻ trải nghiệm.</p></div>}
    {editing && <div className="fixed inset-0 z-[80] grid place-items-center bg-slate-950/55 p-3"><form onSubmit={e => { e.preventDefault(); setEditing(false); }} className="w-full max-w-lg rounded-3xl bg-white p-5 shadow-2xl"><Heading icon={Star} title="Viết / sửa đánh giá" hint="Bản nháp được giữ lại nếu gửi thất bại."/><div className="flex gap-1 text-amber-500 text-2xl">★★★★★</div><textarea required className="mt-4 h-28 w-full rounded-xl border border-slate-200 p-3 text-xs outline-none focus:ring-2 focus:ring-blue-300" placeholder="Chia sẻ trải nghiệm thực tế..."/><div className="mt-3 flex gap-2"><button type="button" onClick={() => setEditing(false)} className="flex-1 rounded-xl border py-2.5 text-xs font-bold text-slate-600">Lưu nháp</button><button className="flex-1 rounded-xl bg-blue-600 py-2.5 text-xs font-bold text-white">Gửi kiểm duyệt</button></div></form></div>}
  </Card>;
}

export function ParentLinkPanel() {
  const [step, setStep] = useState("linked");
  if (step === "linked") return <div className="grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><Card><Heading icon={UserCheck} title="Học sinh đã liên kết" hint="Chỉ dữ liệu của học sinh được xác minh mới hiển thị."/><div className="flex items-center gap-3 rounded-2xl bg-sky-50 p-4"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-blue-600 text-sm font-black text-white">MA</span><div className="flex-1"><p className="text-xs font-black text-slate-800">Nguyễn Minh Anh</p><p className="text-[10px] text-slate-500">Lớp 10A1 · Đã xác minh · Liên kết từ 02/09/2026</p></div><CheckCircle2 className="h-5 w-5 text-emerald-500"/></div><button onClick={() => setStep("request")} className="mt-4 rounded-xl bg-blue-600 px-3 py-2.5 text-xs font-bold text-white">Yêu cầu liên kết học sinh khác</button></Card><Card><Heading icon={ShieldCheck} title="Quyền riêng tư"/><p className="text-[11px] leading-relaxed text-slate-600">Phụ huynh không thể tìm kiếm trẻ em theo tên. Liên kết cần mã do học sinh/nhà trường xác nhận và có thể được thu hồi.</p></Card></div>;
  return <Card className="max-w-2xl"><Heading icon={Users} title="Yêu cầu liên kết học sinh" hint="Mã xác nhận chỉ dùng một lần và hết hạn sau 15 phút."/><div className="grid gap-3 sm:grid-cols-2"><label className="text-[11px] font-bold text-slate-700">Mã liên kết<input className="mt-1.5 w-full rounded-xl border border-slate-200 p-3 font-mono outline-none focus:ring-2 focus:ring-blue-300" placeholder="LINK-XXXX"/></label><label className="text-[11px] font-bold text-slate-700">Ngày sinh học sinh<input type="date" className="mt-1.5 w-full rounded-xl border border-slate-200 p-3 outline-none focus:ring-2 focus:ring-blue-300"/></label></div><div className="mt-4 rounded-xl bg-amber-50 p-3 text-[11px] text-amber-800">Yêu cầu sẽ chờ học sinh hoặc nhà trường xác minh; không hiển thị dữ liệu trước khi xác minh.</div><div className="mt-4 flex gap-2"><button onClick={() => setStep("linked")} className="rounded-xl border px-3 py-2.5 text-xs font-bold text-slate-600">Hủy</button><button onClick={() => setStep("pending")} className="rounded-xl bg-blue-600 px-3 py-2.5 text-xs font-bold text-white">Gửi yêu cầu</button></div>{step === "pending" && <p className="mt-3 text-xs font-bold text-blue-600">Yêu cầu đã tạo · đang chờ xác minh.</p>}</Card>;
}

export function TeacherOperations({ active }) {
  const [classTab, setClassTab] = useState("members"); const [attached, setAttached] = useState(true); const [sent, setSent] = useState(false); const [imported, setImported] = useState(false);
  if (active === "Lớp học") return <Card><Heading icon={Users} title="Lớp HSG Tin 10A1" hint="36 học viên · Thứ Năm 19:30 · giáo viên phụ trách"/><div className="flex gap-1 border-b border-slate-100 pb-3">{[["members","Thành viên"],["attendance","Điểm danh"],["progress","Tiến độ"],["notice","Thông báo"]].map(([id,label]) => <button key={id} onClick={() => setClassTab(id)} className={`rounded-xl px-3 py-2 text-xs font-bold ${classTab === id ? "bg-blue-600 text-white" : "text-slate-600"}`}>{label}</button>)}</div><div className="mt-4">{classTab === "members" && ["Nguyễn Minh Anh", "Trần Đức Long", "Lê Thu Hà"].map((x,i) => <div key={x} className="flex items-center gap-3 border-b border-slate-100 py-3"><span className="grid h-8 w-8 place-items-center rounded-full bg-sky-50 text-[10px] font-bold text-blue-600">{i+1}</span><span className="flex-1 text-xs font-bold text-slate-700">{x}</span><span className="text-[10px] text-emerald-600">Đang học</span></div>)}{classTab === "attendance" && <div className="grid gap-2 sm:grid-cols-3">{["Có mặt 31", "Vắng có phép 03", "Chưa điểm danh 02"].map(x => <div key={x} className="rounded-xl bg-slate-50 p-4 text-xs font-bold text-slate-700">{x}</div>)}</div>}{classTab === "progress" && <div className="rounded-xl bg-sky-50 p-4 text-xs text-slate-700">31/36 học viên hoàn thành bài tuần · <b className="text-blue-600">86% tiến độ</b></div>}{classTab === "notice" && <textarea className="h-24 w-full rounded-xl border border-slate-200 p-3 text-xs" placeholder="Soạn thông báo cho lớp..."/>}</div></Card>;
  if (active === "Học liệu lớp") return <Card><Heading icon={BookOpen} title="Học liệu lớp & quyền dạy" hint="Quyền dạy áp dụng cho mọi lớp phụ trách, không cấp quyền học cá nhân."/><div className="rounded-2xl bg-emerald-50 p-4 text-xs text-emerald-800"><b>Quyền dạy đang hiệu lực đến 30/01/2027</b> · 08 học liệu có thể dùng.</div><div className="mt-4 flex items-center justify-between rounded-2xl border border-slate-100 p-4"><span><b className="block text-xs text-slate-800">Chuyên đề Cấu trúc dữ liệu</b><small className="text-[10px] text-slate-500">Mở theo chương/mục/mã bài · xem trước như học sinh</small></span><button onClick={() => setAttached(!attached)} className={`rounded-xl px-3 py-2 text-xs font-bold ${attached ? "bg-rose-50 text-rose-600" : "bg-blue-600 text-white"}`}>{attached ? "Gỡ khỏi lớp" : "Gắn vào lớp"}</button></div></Card>;
  if (active === "Kho câu hỏi của tôi") return <Card><Heading icon={FileText} title="Kho câu hỏi của tôi" hint="Tách riêng với kho chung · có version và trạng thái phát hành" action={<button className="rounded-xl bg-blue-600 px-3 py-2 text-xs font-bold text-white">+ Tạo câu hỏi</button>}/><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="text-[10px] uppercase text-slate-400"><tr><th className="pb-3">Câu hỏi</th><th>Version</th><th>Trạng thái</th><th className="text-right">Thao tác</th></tr></thead><tbody>{[["DP_023 · Balo nâng cao","v1.3","Đã phát hành"],["GR_014 · Cây khung","v1.1","Bản nháp"],["DS_031 · Segment Tree","v2.0","Chờ duyệt"]].map(row => <tr key={row[0]} className="border-t border-slate-100"><td className="py-3 font-bold text-slate-700">{row[0]}</td><td>{row[1]}</td><td className="text-blue-600">{row[2]}</td><td className="text-right"><button className="font-bold text-blue-600">Sửa</button></td></tr>)}</tbody></table></div></Card>;
  if (active === "Bài tập & Đề") return <div className="grid gap-4 lg:grid-cols-2"><Card><Heading icon={ClipboardCheck} title="Tạo đề hỗn hợp" hint="Chặn phát hành khi thiếu thời gian, quy tắc hoặc câu hỏi."/><div className="space-y-2">{["DP_023 · Code", "GR_014 · Code", "Độ phức tạp · Trắc nghiệm"].map(x => <label key={x} className="flex gap-2 rounded-xl bg-slate-50 p-3 text-xs font-bold text-slate-700"><input type="checkbox" defaultChecked/>{x}</label>)}</div><button className="mt-4 rounded-xl bg-blue-600 px-3 py-2.5 text-xs font-bold text-white">Lưu bản nháp</button></Card><Card><Heading icon={Upload} title="Tải & phân rã đề" hint="Tải Word/PDF → rà soát từng câu trước phát hành."/><div className="rounded-2xl border border-dashed border-sky-200 p-6 text-center"><Upload className="mx-auto h-7 w-7 text-blue-400"/><p className="mt-2 text-xs font-bold text-slate-700">Thả tệp đề vào đây</p><button onClick={() => setImported(true)} className="mt-3 text-xs font-bold text-blue-600">Chọn tệp mô phỏng</button></div>{imported && <div className="mt-3 rounded-xl bg-emerald-50 p-3 text-[11px] text-emerald-700">Đã phân rã 12 câu · 2 câu cần rà soát cấu hình.</div>}</Card></div>;
  if (active === "Giao đề") return <Card><Heading icon={Send} title="Giao đề đánh giá" hint="Không hỗ trợ ngoại lệ theo từng học sinh."/><div className="grid gap-3 sm:grid-cols-2">{[["Lớp nhận đề","Lớp HSG Tin 10A1"],["Đề được chọn","Đề tuần 5: Cây & Đồ thị"],["Mở đề","16/09/2026 14:00"],["Đóng đề","16/09/2026 17:00"]].map(([a,b]) => <label key={a} className="rounded-xl bg-slate-50 p-3"><span className="block text-[10px] font-bold text-slate-400">{a}</span><span className="mt-1 block text-xs font-bold text-slate-700">{b}</span></label>)}</div><button onClick={() => setSent(true)} className="mt-4 rounded-xl bg-blue-600 px-4 py-2.5 text-xs font-bold text-white">Lên lịch giao đề</button>{sent && <p className="mt-3 text-xs font-bold text-emerald-600">Đề đã lên lịch · trạng thái: Chờ mở.</p>}</Card>;
  if (active === "Kết quả") return <Card><Heading icon={FileCheck2} title="Kết quả theo lớp" hint="Phễu: lớp → đề → học sinh → lần nộp." action={<button className="flex items-center gap-1 text-xs font-bold text-blue-600"><Download className="h-4 w-4"/>Xuất báo cáo</button>}/><div className="mb-3 flex gap-2 text-[10px] font-bold"><span className="rounded-full bg-slate-100 px-2 py-1">Chưa làm 04</span><span className="rounded-full bg-amber-50 px-2 py-1 text-amber-700">Đang làm 02</span><span className="rounded-full bg-emerald-50 px-2 py-1 text-emerald-700">Đã nộp 30</span></div><div className="overflow-x-auto"><table className="w-full text-left text-xs"><tbody>{[["Nguyễn Minh Anh","Lần nộp #2","92","Accepted"],["Trần Đức Long","Lần nộp #1","78","Đang chấm"],["Lê Thu Hà","—","—","Chưa làm"]].map(r => <tr key={r[0]} className="border-t border-slate-100"><td className="py-3 font-bold text-slate-700">{r[0]}</td><td>{r[1]}</td><td>{r[2]}</td><td className="font-bold text-blue-600">{r[3]}</td></tr>)}</tbody></table></div></Card>;
  return null;
}

export function SystemStatesPanel() { return <Card><Heading icon={AlertCircle} title="Trạng thái hệ thống" hint="Bộ state dùng chung cho list, form và quyền."/><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><div className="rounded-2xl bg-slate-50 p-4"><div className="h-3 w-24 animate-pulse rounded bg-slate-200"/><div className="mt-3 h-2 w-full animate-pulse rounded bg-slate-200"/><p className="mt-4 text-[10px] font-bold text-slate-500">Loading skeleton</p></div><div className="rounded-2xl border border-dashed border-sky-200 p-4"><Archive className="h-5 w-5 text-sky-400"/><p className="mt-2 text-xs font-bold text-slate-700">Chưa có dữ liệu</p><p className="text-[10px] text-slate-500">Tạo nội dung đầu tiên.</p></div><div className="rounded-2xl bg-rose-50 p-4"><CloudOff className="h-5 w-5 text-rose-500"/><p className="mt-2 text-xs font-bold text-rose-700">Lỗi mạng</p><button className="mt-2 flex items-center gap-1 text-[10px] font-bold text-rose-700"><RefreshCw className="h-3 w-3"/>Thử lại</button></div><div className="rounded-2xl bg-amber-50 p-4"><LockKeyhole className="h-5 w-5 text-amber-600"/><p className="mt-2 text-xs font-bold text-amber-800">Bạn không có quyền</p><p className="text-[10px] text-amber-700">Liên hệ quản trị viên.</p></div></div></Card>; }
